name: hereme_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.2
  image_picker: ^0.6.0+2
  cached_network_image: ^0.8.0
  firebase_auth: ^0.10.0+1
  firebase_core: ^0.4.0
  firebase_database: ^3.0.7
  firebase_storage: ^3.0.0
  shared_preferences: ^0.5.2
  cloud_firestore: ^0.12.9+5
  image_cropper: ^1.0.1
  location: ^2.3.5
  font_awesome_flutter: ^8.5.0
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.3
  flushbar: ^1.8.2
  uuid: ^2.0.2
  time_ago_provider: ^1.0.3
  async: ^2.2.0
  intl: ^0.16.0
  geolocator: ^5.1.4+1
  permission_handler: ^3.2.2
  geoflutterfire: ^2.0.3+5
  launch_review: ^2.0.0
  animator: ^1.0.0+1
  share: ^0.6.3+1
  firebase_messaging: ^5.1.8
  flutter_google_ad_manager: ^0.10.1
#  firebase_admob: ^0.9.0+9
#  admob_flutter: ^0.3.1ad

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
       - family: Berlin-Sans
         fonts:
             - asset: fonts/Berlin-Sans.ttf

       - family: Arimo
         fonts:
             - asset: fonts/Arimo-Regular.ttf

  uses-material-design: true

  assets:
    - images/
    - images/SocialMedias/